name: 'Configure AWS Credentials'
description: 'Configures AWS credentials using OIDC for b-onsite projects'
branding:
  icon: 'cloud'
  color: 'orange'

inputs:
  role-to-assume:
    description: 'AWS IAM role ARN to assume'
    required: false
    default: 'arn:aws:iam::736766805372:role/bos-common-shared_infra-gha-trust'
  aws-region:
    description: 'AWS region'
    required: false
    default: 'eu-central-1'

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
