name: 'Upload Lambda Package to S3'
description: 'Uploads Lambda deployment package to S3 with versioning and tagging'
branding:
  icon: 'upload'
  color: 'orange'

inputs:
  package-file:
    description: 'Path to the Lambda package zip file'
    required: true
  s3-bucket:
    description: 'S3 bucket name'
    required: true
  s3-key:
    description: 'S3 object key (path within bucket)'
    required: true
  version-tag:
    description: 'Version tag to apply to the S3 object'
    required: true

outputs:
  version-id:
    description: 'S3 object version ID'
    value: ${{ steps.upload.outputs.version-id }}
  s3-uri:
    description: 'Full S3 URI (s3://bucket/key)'
    value: ${{ steps.upload.outputs.s3-uri }}

runs:
  using: 'composite'
  steps:
    - name: Upload package to S3
      id: upload
      shell: bash
      run: |
        echo "Uploading Lambda package to S3..."
        echo "- Bucket: ${{ inputs.s3-bucket }}"
        echo "- Key: ${{ inputs.s3-key }}"
        echo "- Version tag: ${{ inputs.version-tag }}"

        # Upload package with versioning and tagging
        VERSION_ID=$(aws s3api put-object \
          --bucket "${{ inputs.s3-bucket }}" \
          --key "${{ inputs.s3-key }}" \
          --body "${{ inputs.package-file }}" \
          --tagging "version=${{ inputs.version-tag }}" \
          --query 'VersionId' \
          --output text)

        if [ -z "$VERSION_ID" ]; then
          echo "❌ Failed to upload package to S3"
          exit 1
        fi

        # Output results
        echo "version-id=$VERSION_ID" >> $GITHUB_OUTPUT
        echo "s3-uri=s3://${{ inputs.s3-bucket }}/${{ inputs.s3-key }}" >> $GITHUB_OUTPUT

        echo "✅ Package uploaded successfully"
        echo "- Version ID: $VERSION_ID"
        echo "- S3 URI: s3://${{ inputs.s3-bucket }}/${{ inputs.s3-key }}"
