name: 'Deploy to ECS'
description: 'Deploys a Docker image to AWS ECS by updating task definition and service'
branding:
  icon: 'upload-cloud'
  color: 'orange'

inputs:
  ecr-image:
    description: 'Full ECR image URI with tag (e.g., 123456789012.dkr.ecr.eu-central-1.amazonaws.com/repo:tag)'
    required: true
  task-family:
    description: 'ECS task definition family name'
    required: true
  cluster-name:
    description: 'ECS cluster name'
    required: true
  service-name:
    description: 'ECS service name'
    required: true
  task-def-ssm-param:
    description: 'SSM parameter name containing the task definition template ARN'
    required: true
  container-index:
    description: 'Index of the container in the task definition to update (default: 0)'
    required: false
    default: '0'

outputs:
  task-definition-arn:
    description: 'ARN of the newly registered task definition'
    value: ${{ steps.register-task-def.outputs.task-definition-arn }}

runs:
  using: 'composite'
  steps:
    - name: Register task definition
      id: register-task-def
      uses: BConsultingKft/b-gh-actions/ecs-register-task-definition@main
      with:
        ecr-image: ${{ inputs.ecr-image }}
        task-family: ${{ inputs.task-family }}
        task-def-ssm-param: ${{ inputs.task-def-ssm-param }}
        container-index: ${{ inputs.container-index }}

    - name: Update ECS service
      uses: BConsultingKft/b-gh-actions/ecs-update-service@main
      with:
        cluster-name: ${{ inputs.cluster-name }}
        service-name: ${{ inputs.service-name }}
        task-definition-arn: ${{ steps.register-task-def.outputs.task-definition-arn }}

    - name: Summary
      shell: bash
      run: |
        echo "✅ ECS service updated successfully"
        echo "- Cluster: ${{ inputs.cluster-name }}"
        echo "- Service: ${{ inputs.service-name }}"
        echo "- Image: ${{ inputs.ecr-image }}"
        echo "- Task Definition: ${{ steps.register-task-def.outputs.task-definition-arn }}"